### ISSUE TITLE
Problem with AppGelegate.swift

### ISSUE THREAD

**Issue by ivangalkindeveloper** [mix1009/FlutterDropbox#16]
Problem with AppDelegate.swift file.

The source file has the following code:
```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

After the change according to the documentation:
```
import UIKit
import Flutter
import ObjectiveDropboxOfficial

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _application: UIApplication,
    open url: URL,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> bool {
    if let authResult = DBClientsManager.handleRedirectURL(url) {
      if authResult.isSuccess() {
          print("dropbox auth success")
      } else if (authResult.isCancel()) {
          print("dropbox auth cancel")
      } else if (authResult.isError()) {
          print("dropbox auth error \(authResult.errorDescription)")
      }
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

I am getting an error:

```
    Writing result bundle at path:
    /var/folders/2g/ycm43f9500133_g_pdg_cq640000gn/T/flutter_tools.8hWmka/flutter_ios_build_temp_dirqBUXLe/temporary_xcresult_bundle
    /Users/ivangalkin/Development/My projects/BReminder/ios/Runner/AppDelegate.swift:7:17: error: method does not override any method from its superclass
      override func application(
      ~~~~~~~~^
    /Users/ivangalkin/Development/My projects/BReminder/ios/Runner/AppDelegate.swift:12:63: error: missing argument for parameter 'completion' in call
        if let authResult = DBClientsManager.handleRedirectURL(url) {
                                                                  ^
                                                                  , completion: <#DBOAuthCompletion#>
    ObjectiveDropboxOfficial.DBClientsManager:13:21: note: 'handleRedirectURL(_:completion:)' declared here
        open class func handleRedirectURL(_ url: URL, completion: @escaping DBOAuthCompletion) -> Bool
                        ^uthCompletion) -> Bool
                        ^
```

**Comment by jebastindev** [comment]
> Problem with AppDelegate.swift file.
> 
> The source file has the following code:
> 
> ```
> import UIKit
> import Flutter
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> bool {
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```
> 
> After the change according to the documentation:
> 
> ```
> import UIKit
> import Flutter
> import ObjectiveDropboxOfficial
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _application: UIApplication,
>     open url: URL,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> bool {
>     if let authResult = DBClientsManager.handleRedirectURL(url) {
>       if authResult.isSuccess() {
>           print("dropbox auth success")
>       } else if (authResult.isCancel()) {
>           print("dropbox auth cancel")
>       } else if (authResult.isError()) {
>           print("dropbox auth error \(authResult.errorDescription)")
>       }
>     }
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```
> 
> I am getting an error:
> 
> ```
>     Writing result bundle at path:
>     /var/folders/2g/ycm43f9500133_g_pdg_cq640000gn/T/flutter_tools.8hWmka/flutter_ios_build_temp_dirqBUXLe/temporary_xcresult_bundle
>     /Users/ivangalkin/Development/My projects/BReminder/ios/Runner/AppDelegate.swift:7:17: error: method does not override any method from its superclass
>       override func application(
>       ~~~~~~~~^
>     /Users/ivangalkin/Development/My projects/BReminder/ios/Runner/AppDelegate.swift:12:63: error: missing argument for parameter 'completion' in call
>         if let authResult = DBClientsManager.handleRedirectURL(url) {
>                                                                   ^
>                                                                   , completion: <#DBOAuthCompletion#>
>     ObjectiveDropboxOfficial.DBClientsManager:13:21: note: 'handleRedirectURL(_:completion:)' declared here
>         open class func handleRedirectURL(_ url: URL, completion: @escaping DBOAuthCompletion) -> Bool
>                         ^uthCompletion) -> Bool
>                         ^
> ```

its working try it  
override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
           //        let oauthCompletion: DBOAuthCompletion()
           DBClientsManager.handleRedirectURL(url) {authResult in
               
           }
           return true
       }

**Comment by mix1009** [comment]
Please update the code to:

>         override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>           DBClientsManager.handleRedirectURL(url, completion:{ (authResult) in
>             if let authResult = authResult {
>                 if authResult.isSuccess() {
>                     print("dropbox auth success")
>                 } else if (authResult.isCancel()) {
>                     print("dropbox auth cancel")
>                 } else if (authResult.isError()) {
>                     print("dropbox auth error \(authResult.errorDescription)")
>                 }
>             }
>           });
>           return true
>         }
> 

ObjectiveDropboxOfficial library changed their API around version 5.0.2.
