### ISSUE TITLE
Enable short-lived access token OAUTH flow, please!

### ISSUE THREAD

**Issue by ToH2002** [mix1009/FlutterDropbox#17]
Since Dropbox doesn't allow long-lived access tokens anymore, I believe the package needs to be updated to the new authorization flow:

https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens

Currently, if I save a token in shared preferences and keep using it, I simply get empty responses on all of my requests. My app needs to identify this issue from the empty responses and then initiate the re-authorize in my app to keep accessing my Dropbox. This should be done automatically without the need of user intervention in most cases, as per the above article.

At the minimum, could you at least enable some error messaging from the methods like listFolder, so my app can know for sure that the token has expired and kick off a manual re-authorization flow?

**Comment by MeghanKharva** [comment]
I am also getting same issue.

**Comment by ToH2002** [comment]
I have implemented the new PKCE-based authentication in a local copy of the plugin, so it can be made to work. Since I don't have a Mac (yet), I can't implement the equivalent changes on the iOS side of things, so reluctant to get involved in a pull request. 

I'd prefer the original author to update the plugin, so it all stays under control. Happy to help, though if the author is interested.

**Comment by mix1009** [comment]
@ToH2002 I'm open the pull requests. I'll also consider implementing it for iOS. Thank you.

**Comment by ToH2002** [comment]
OK, pull request is initiated - hope this works (this is my first pull request 😉 ).

Great if you could pick up on this and implement the relevant parts for iOS!

Cheers,

Torsten

**Comment by mix1009** [comment]
Thank you. I'll look into it, and try to implement PKCE for iOS.

**Comment by ToH2002** [comment]
@mix1009 : I think you could delete my README-TE.md file - that was just for your information ;-)
