### ISSUE TITLE
Redirect URIs issue

### ISSUE THREAD

**Issue by mlava** [mix1009/FlutterDropbox#31]
Hi all.
Sorry to ask what probably seems obvious to most.
Does this plugin handle redirects? If so, what do I need to set in the Redirect URIs section of the https://www.dropbox.com/developers page for my app?
Thanks in advance.

**Comment by SunilKividor** [comment]
It does handle without any redirects mentioned in the developers page . But I am having an issue in IOS, its not redirecting in IOS

**Comment by mlava** [comment]
Thank you @SunilKividor
What do I need to put in the app settings at Dropbox dev page?
Cheers!

**Comment by SunilKividor** [comment]
check your inapp AndroidManifest file configuration , refer to the docs mentioned for this package.

**Comment by mlava** [comment]
Thanks @SunilKividor 
I now have it working on both Android and iOS. I think for Android I needed to fix my manifest.
Cheers!
