### ISSUE TITLE
Any update to flutter 1.1 7 ? Swift

### ISSUE THREAD

**Issue by manuelabarca** [mix1009/FlutterDropbox#4]
Any update for to use in AppDelegate.swift ? or idea, thanks.

**Comment by ascot01** [comment]
I'm also interested in such an update.

**Comment by mix1009** [comment]
Try updating AppDelegate.swift to:

```
import UIKit
import Flutter
import ObjectiveDropboxOfficial


@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    if let authResult = DBClientsManager.handleRedirectURL(url) {
        if authResult.isSuccess() {
            print("dropbox auth success")
        } else if (authResult.isCancel()) {
            print("dropbox auth cancel")
        } else if (authResult.isError()) {
            print("dropbox auth error \(authResult.errorDescription)")
        }
    }
    return true
  }

}
```

I'll update documentation.

**Comment by manuelabarca** [comment]
> Try updating AppDelegate.swift to:
> 
> ```
> import UIKit
> import Flutter
> import ObjectiveDropboxOfficial
> 
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
>     
>   override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>     if let authResult = DBClientsManager.handleRedirectURL(url) {
>         if authResult.isSuccess() {
>             print("dropbox auth success")
>         } else if (authResult.isCancel()) {
>             print("dropbox auth cancel")
>         } else if (authResult.isError()) {
>             print("dropbox auth error \(authResult.errorDescription)")
>         }
>     }
>     return true
>   }
> 
> }
> ```
> 
> I'll update documentation.

Thank you !
