### ISSUE TITLE
don't know how to InitDropbox()

### ISSUE THREAD

**Issue by fenchai23** [mix1009/FlutterDropbox#6]
how do I get the client id?
what is this dropbox key?
where is the dropbox secret?

I only know where the TOKEN is. the rest, I'm blind

```
Future initDropbox() async {
    // init dropbox client. (call only once!)
    await Dropbox.init(dropbox_clientId, dropbox_key, dropbox_secret);
}
```

**Comment by mix1009** [comment]
You need to create an app from Dropbox. 

https://www.dropbox.com/developers/apps/create

After creating it, App key and App secret is available from "Settings" tab.

clientId can be set as you want. 
<img width="1047" alt="Screen Shot 2020-10-16 at 3 44 17 PM" src="https://user-images.githubusercontent.com/1288793/96224475-9dc9f180-0fca-11eb-85ed-3afcb9b40cc8.png">

**Comment by fenchai23** [comment]
> You need to create an app from Dropbox. 
> 
> https://www.dropbox.com/developers/apps/create
> 
> After creating it, App key and App secret is available from "Settings" tab.
> 
> clientId can be set as you want. 
> <img width="1047" alt="Screen Shot 2020-10-16 at 3 44 17 PM" src="https://user-images.githubusercontent.com/1288793/96224475-9dc9f180-0fca-11eb-85ed-3afcb9b40cc8.png">
> 
> 

and clientID?

**Comment by mix1009** [comment]
clientId can be set as you want. I guess it's for debugging/logging purposes.

**Comment by fenchai23** [comment]
I see, thank you for your guidance.
